### ISSUE TITLE
Astronomical Death Count

### ISSUE THREAD

**Issue by irbyjm** [RiotNOR/Soulslike-Death-Counter#1]
I'm running the death counter and it is reporting that my number of deaths is 1081341760. 
![image](https://user-images.githubusercontent.com/12702340/56711903-6abae080-66fa-11e9-8e5d-f68e6d0851b9.png)
I'm bad... but I don't think I'm that bad?

I tried troubleshooting this myself but my debugging skills are rusty and I don't know C#. 😦

**Comment by RiotNOR** [comment]
There may have been an update. I'll publish an update myself later today. 'scuse my tardiness.

**Comment by RiotNOR** [comment]
Fixed in https://github.com/RiotNOR/Soulslike-Death-Counter/commit/70c68c91a46b092b9f3ebb6b1f490c751d1d3305

**Comment by irbyjm** [comment]
Okay now it's too accurate. 
![image](https://user-images.githubusercontent.com/12702340/56855297-e0999480-6912-11e9-947e-ccfefb7e88d5.png)
Cheers!
